image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

stages:          # List of stages for jobs, and their order of execution
  - test
  - deploy

before_script:
  - cd ./webapp
  - python --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  - pip install flake8
  - pip install pytest

test-job:   # This job runs in the test stage.
  stage: test
  script:
    - echo "Running lint tests..."
    - flake8 --ignore=E501 --exclude=venv* --statistics
    - echo "Running unit tests..."
    - pytest -v

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
